# -*- coding: utf-8 -*-
"""VirtuDockDL (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_ELaTTF-zh8rMTMS8Vu4ecmeUo8cXZ6
"""

!pip install -q condacolab
import condacolab; condacolab.install()
!conda install -c conda-forge pdbfixer -y -q

!pip install dgl==1.1.3 -q

!pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 -q

!pip install --ignore-installed blinker flask -q
!pip install pandas "numpy<2.0" scikit-learn matplotlib rdkit biopython -q
!pip install openmm -q
!pip install torch_geometric -q
!pip install pyyaml pydantic -q
!pip install flask -q
!pip install mdtraj -q
!apt install openbabel -y -q
!pip install flask-cors -q
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

# Commented out IPython magic to ensure Python compatibility.
# # Baixando e extraindo o Autodock Vina do SCRIPPS
# # Em seguida, configuramos um alias para o vina ser tratado como um binário nativo
# %%bash
# wget --no-check-certificate https://vina.scripps.edu/wp-content/uploads/sites/55/2020/12/autodock_vina_1_1_2_linux_x86.tgz
# tar xzvf autodock_vina_1_1_2_linux_x86.tgz
# rm autodock_vina_1_1_2_linux_x86.tgz

# Configurando o caminho para o Autodock Vina
import os
os.environ['PATH'] += ":/content/autodock_vina_1_1_2_linux_x86/bin"

!git clone  https://github.com/klocke3/VirtuDockDL_Colab

import os
os.environ['MPLBACKEND'] = 'Agg'

!pkill cloudflared || echo "OK"
!rm -f cloudflared.log || echo "OK"
!python /content/VirtuDockDL_Colab/app.py

!rm -rf /content/VirtuDockDL_Colab/
!rm -rf /content/docking_results
!rm -rf /content/generated_files
!rm -rf /content/static
!rm -rf /content/uploaded_files
!rm -rf /content/uploads

# 1. Download do Executável do GNINA
# Usamos o prefixo '!' que é mais direto no Colab.
!wget -O /content/gnina https://github.com/gnina/gnina/releases/download/v1.0.3/gnina

# 2. Tornar Executável (usando o caminho completo)
!chmod +x ./gnina

# 3. Testar a execução usando o caminho completo
!./gnina --version
